
gitDirectory: /tmp/git
salesforceDirectory: /tmp/salesforce
backupDirectory: /tmp/backup

# gitDirectory: d:\\tmp\\git
# salesforceDirectory: d:\\tmp\\salesforce
# backupDirectory: d:\\tmp\\backup

clientKey: 3MVG9ZL0ppGP5UrC6uYG2F8MedFD2Yiy1y1KUpVsNmHUUqK6dqQSnZ05fwAtUkKX5k4zD.lbR2Tx4O.PuMfsY
clientSecret: 1533324426739765893

database:
  url: jdbc:h2:./target/app
  driverClass: org.h2.Driver

  properties:
    hibernate.hbm2ddl.auto: create