
gitDirectory: /tmp/git
salesforceDirectory: /tmp/salesforce
backupDirectory: /tmp/backup

# gitDirectory: d:\\tmp\\git
# salesforceDirectory: d:\\tmp\\salesforce
# backupDirectory: d:\\tmp\\backup

database:
  url: jdbc:h2:mem:test
  driverClass: org.h2.Driver

  properties:
    hibernate.hbm2ddl.auto: create